# Generated by Django 5.2.10 on 2026-01-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username_changed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last username change. Used for rate limiting.', null=True, verbose_name='username changed at'),
        ),
    ]
