# Generated by Django 5.2.10 on 2026-01-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_add_username_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_expires',
            field=models.DateTimeField(blank=True, help_text='Token expiry time (24 hours after creation).', null=True, verbose_name='email verification expires'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='UUID token for email verification.', max_length=36, null=True, verbose_name='email verification token'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pending_email',
            field=models.EmailField(blank=True, help_text='New email address awaiting verification.', max_length=254, null=True, verbose_name='pending email'),
        ),
    ]
