# Generated by Django 5.2.10 on 2026-01-28 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_add_email_change_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='UUID token for email verification.', max_length=36, verbose_name='email verification token'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pending_email',
            field=models.EmailField(blank=True, help_text='New email address awaiting verification.', max_length=254, verbose_name='pending email'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='diary.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this post. Will be automatically resized.', max_length=200, upload_to='diary/images/'),
        ),
    ]
