# Generated by Django 5.2.10 on 2026-01-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_add_related_names_and_fix_image_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at'], 'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RenameField(
            model_name='like',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_request',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username_changed_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last activity at'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username_last_changed',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last username change. Used for rate limiting.', null=True, verbose_name='username last changed'),
        ),
    ]
